[package]
name = "carla-src"
version = "0.2.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
description = "A utility crate that prepares Carla simulator source code"
edition = "2021"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/jerry73204/carla-rust"
repository = "https://github.com/jerry73204/carla-rust"
documentation = "https://docs.rs/carla-src/"

[dependencies]
anyhow = "1.0.66"
autotools = "0.2.5"
cfg-if = "1.0.0"
cmake = "0.1.49"
flate2 = "1.0.25"
hex = { version = "0.4.3", features = ["serde"] }
itertools = "0.10.5"
json5 = "0.4.1"
log = "0.4.17"
native-tls = "0.2.11"
safe-transmute = "0.11.2"
serde = { version = "1.0.148", features = ["derive"] }
sha2 = "0.10.6"
tar = "0.4.38"
ureq = { version = "2.5.0", features = ["native-tls"] }
