[package]
name = "carla-sys"
version = "0.4.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
description = "FFI bindings for Carla simulator"
edition = "2021"
links = "carla"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/jerry73204/carla-rust"
repository = "https://github.com/jerry73204/carla-rust"
documentation = "https://docs.rs/carla-sys/"

[dependencies]
autocxx = { version = "0.23.1" }
cxx = "1.0.82"

[build-dependencies]
autocxx-build = { version = "0.23.1" }
carla-bin = { version = "0.1.1", path = "../carla-bin" }
carla-src = { version = "0.2.1", path = "../carla-src" }

[features]
docs-only = []

[package.metadata.docs.rs]
no-default-features = true
features = ["docs-only"]
