[package]
name = "carla-sys"
version = "0.1.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
description = "FFI bindings for Carla simulator"
edition = "2021"
links = "carla"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/jerry73204/carla"
repository = "https://github.com/jerry73204/carla"
documentation = "https://docs.rs/carla-sys/"

[dependencies]
autocxx = "0.23.1"
cfg-if = "1.0.0"
cxx = "1.0.82"

[build-dependencies]
autocxx-build = "0.23.1"
pkg-config = "0.3.26"
carla-src = { version = "0.1.0", path = "../carla-src" }

[features]
docs-only = []
save-bindings = []

[package.metadata.docs.rs]
no-default-features = true
features = ["docs-only"]
