[package]
name = "carla"
version = "0.1.0"
edition = "2021"

[dependencies]
autocxx = "0.23.1"
cxx = "1.0.82"
nalgebra = "0.31.4"
carla-sys = { version = "0.1.0", path = "../carla-sys" }
ndarray = "0.15.6"
once_cell = "1.16.0"
anyhow = "1.0.66"
itertools = "0.10.5"
derivative = "2.2.0"
