[package]
name = "carla"
version = "0.3.1"
authors = ["jerry73204 <jerry73204@gmail.com>"]
description = "Rust client library for Carla simulator"
edition = "2021"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/jerry73204/carla-rust"
repository = "https://github.com/jerry73204/carla-rust"
documentation = "https://docs.rs/carla/"

[dependencies]
autocxx = "0.23.1"
cxx = "1.0.82"
nalgebra = "0.31.4"
carla-sys = { version = "0.3.0", path = "../carla-sys" }
ndarray = "0.15.6"
once_cell = "1.16.0"
anyhow = "1.0.66"
itertools = "0.10.5"
derivative = "2.2.0"

[features]
docs-only = ["carla-sys/docs-only"]

[package.metadata.docs.rs]
no-default-features = true
features = ["docs-only"]
