[package]
name = "carla"
version = "0.8.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
description = "Rust client library for Carla simulator"
edition = "2021"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/jerry73204/carla-rust"
repository = "https://github.com/jerry73204/carla-rust"
documentation = "https://docs.rs/carla/"

[dependencies]
autocxx = "0.25.0"
cxx = "1.0.95"
nalgebra = "0.32.2"
carla-sys = { version = "0.8.0", path = "../carla-sys" }
ndarray = "0.15.6"
once_cell = "1.17.1"
anyhow = "1.0.71"
itertools = "0.10.5"
derivative = "2.2.0"
static_assertions = "1.1.0"

[features]
docs-only = ["carla-sys/docs-only"]
force-rebuild = ["carla-sys/force-rebuild"]

[package.metadata.docs.rs]
no-default-features = true
features = ["docs-only"]
