[package]
name = "carla-bin"
version = "0.1.1"
authors = ["jerry73204 <jerry73204@gmail.com>"]
description = "Prepare and build Carla simulator source code."
edition = "2021"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/jerry73204/carla-rust"
repository = "https://github.com/jerry73204/carla-rust"
documentation = "https://docs.rs/carla-bin/"

[build-dependencies]
carla-src = { version = "0.2.1", path = "../carla-src" }
cfg-if = "1.0.0"

[dependencies]
anyhow = "1.0.66"
once_cell = "1.16.0"
carla-src = { version = "0.2.1", path = "../carla-src" }

[features]
force-rebuild = []
generate-prebuild = []
